/**
 * The single API contract, shared by the route handlers and the client.
 *
 * These replace 14 near-duplicate interface declarations spread across 7 files
 * — four `Transaction`s that disagreed with each other, four `Account`s, two
 * `MonthlyBudget`s, and four copies of the account-update payload — plus the
 * two stale files in this directory (`transaction.ts` declared `merchant` and
 * `accountId`, neither of which the API has ever returned).
 *
 * Rules:
 *  - Field names match the database columns exactly (snake_case). No renaming
 *    at the boundary; `card.ts` renaming `max`/`balance` to `limit`/`value` is
 *    what made the data model confusing to follow.
 *  - Money arrives from `pg` as a string (numeric) and is coerced with
 *    `Number()` at the route boundary, so these types are what the client
 *    actually receives, post-serialization.
 */

/** Values of the Postgres enum `public."Category"`. Always lowercase. */
export const CATEGORY_VALUES = [
  "income",
  "grocery",
  "food",
  "tech",
  "transportation",
  "entertainment",
  "bills",
  "misc",
] as const

export type Category = (typeof CATEGORY_VALUES)[number]

// ---------------------------------------------------------------------------
// Rows as the API returns them
// ---------------------------------------------------------------------------

export interface Account {
  id: string
  name: string | null
  type: string | null
  balance: number
  /** Credit limit for credit accounts; cumulative income for all others. */
  max: number
  archived: boolean
}

export interface Transaction {
  id: string
  /** `YYYY-MM-DD` — a Postgres `date`, with no time or zone. */
  date: string
  amount: number
  description: string
  category: Category
  created_at: string | null
  account_id: string
  /** Set only on rows generated by the recurring-payments job. */
  recurring_payment_id: number | null
  period_year: number | null
  period_month: number | null
}

export interface MonthlyBudget {
  month: number
  base_budget: number
}

export interface BalanceSnapshot {
  id: string
  /** Previous month's ending balance plus this month's base budget. */
  starting_balance: number
  ending_balance: number | null
  month: number
  year: number
}

/**
 * A year's starting/ending balance, from GET /api/balance_snapshot?year=.
 *
 * Derived from the year's January and December rows in
 * monthly_balance_snapshot — there is no per-year row. Either field is null
 * when its month's row does not exist yet (e.g. December hasn't closed).
 */
export interface YearBalanceSummary {
  year: number
  starting_balance: number | null
  ending_balance: number | null
}

/** One month's totals, from GET /api/transactions/monthly_totals. */
export interface MonthlyTotal {
  year: number
  /** 1-12. */
  month: number
  income: number
  expenses: number
}

export interface RecurringPayment {
  id: number
  amount: number
  day_of_month: number
  description: string | null
  account_id: string | null
  /** Title Case here, unlike `Transaction.category`. See lib/categories.ts. */
  category: string
  created_at: string | null
  updated_at: string | null
}

// ---------------------------------------------------------------------------
// Request bodies
// ---------------------------------------------------------------------------

export type AccountCreateBody = {
  name: string
  type: string
  balance: number
  max: number
}

export type AccountUpdateBody = Partial<AccountCreateBody> & { id: string }

export type TransactionCreateBody = {
  date: string
  amount: number
  description?: string
  category: string
  account_id: string
}

export type TransactionUpdateBody = Partial<TransactionCreateBody> & { id: string }

export type MonthlyBudgetUpdateBody = {
  month: number
  base_budget: number
}

export type RecurringPaymentCreateBody = {
  amount: number
  day_of_month: number
  description?: string
  account_id: string
  category: string
}

export type RecurringPaymentUpdateBody = Partial<RecurringPaymentCreateBody> & { id: number }

// ---------------------------------------------------------------------------
// Response envelopes
// ---------------------------------------------------------------------------

/**
 * Mutating transaction routes return the affected account rows alongside the
 * transaction, so the client never has to re-derive a balance locally.
 */
export type WithAccounts<T> = T & { accounts: Account[] }

export type ErrorResponse = { error: string }

/** The subset of an account the transaction pickers need. */
export type AccountOption = Pick<Account, "id" | "name" | "type">
