version: "3.9"

services:
  app:
    build: .
    container_name: finance_app
    ports:
      - "3000:3000"
    env_file:
      - .env

  worker:
    build: .
    container_name: finance_worker
    command: ["node", "worker.mjs"]
    env_file:
      - .env
